{
 "title": "Dom",
 "description": "🏠 z panelami skierowanymi na zachód",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Moc Teoretyczna Maksymalna",
   "type": "stat",
   "description": "Moc instalacji fotowoltaicznej to moc określona dla tzw. warunków STC (Standard Test Conditions). Moc instalacji PV podajemy w Watt-pikach [Wp lub kWp=1000Wp]. W warunkach polskich można przyjąć, iż moc instalacji wyrażona w kWp to moc maksymalna instalacji.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "capacity=Nominalna_Wydajnosc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wysokość Słońca na horyzoncie",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Stopnie" }
   ],
   "targets": [
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "W tym roku wytworzono",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=yearly",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Power=severity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarm opis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Power=alarms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Odpowiednik zasadzenia",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=yearly",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *0.0117" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Całkowita produkcja prądu",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "Dziś",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power=day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Aktualny miesiąc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power=month",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Od początku",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power=total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produkcja prądu godzinowo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "KW/h" }
   ],
   "targets": [
    {
     "alias": "Produkcja prądu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=hourly",
     "query": "SELECT mean(\"value\") FROM \"Power=hourly\" WHERE $timeFilter GROUP BY time($__interval) fill(none) tz('UTC')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "UTC"
    }
   ]
  },
  {
   "title": "Produkcja prądu dziennie",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "KW/h" }
   ],
   "targets": [
    {
     "alias": "Produkcja prądu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Power=daily",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Strata na konwersji DC/AC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=perpower_ratio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produkcja prądu miesięcznie",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "megwatt", "label": "MW/h" }
   ],
   "targets": [
    {
     "alias": "Produkcja prądu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=monthly",
     "query": "SELECT mean(\"value\")  /1000 FROM \"Power=monthly\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " /1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Strata na konwersji DC/AC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=monthly_perpower_ratio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " /1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produkcja prądu rocznie",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "alias": "Produkcja prądu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power=yearly",
     "query": "SELECT mean(\"value\")  /1000 FROM \"Power=monthly\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Strata na konwersji DC/AC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power=yearly_perpower_ratio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ochrona środowiska dziennie",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "masskg", "label": " Niewyemitowany Co2" }
   ],
   "targets": [
    {
     "alias": "Niewyemitowany CO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=daily",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " /1000*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Zaoszczędzony węgiel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Power=daily",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " /1000* 0.34*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ochrona środowiska miesięcznie",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "masst", "label": " Niewyemitowany Co2" }
   ],
   "targets": [
    {
     "alias": "Niewyemitowany CO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=monthly",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Zaoszczędzony węgiel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=monthly",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/ 1000*0.34" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ochrona środowiska rocznie",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "alias": "Niewyemitowany CO2 🏭︎",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power=yearly",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Zaoszczędzony węgiel ⛏",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power=yearly",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000*0.34" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wartoś wyprodukowanego prądu",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "alias": "Miesięcznie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=monthly",
     "query": "SELECT mean(\"value\")  *80/100*0.59 FROM \"Power=monthly\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *0.59" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Rocznie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power=yearly",
     "query": "SELECT mean(\"value\")  *80/100*0.59 FROM \"Power=monthly\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "  *0.59" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}